# Generated by Django 4.2.11 on 2024-03-14 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_main.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('condition_when_checked_out', models.CharField(max_length=100)),
                ('condition_when_checked_at', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_main.device')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_main.employee')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Log',
                'db_table': 'device_log',
            },
        ),
    ]
